### ISSUE TITLE
bins can have either centers or ranges, both is not required

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/verifier-nodejs#3]
The verifier flags 

http://tsds.org/verify-hapi/?url=http://jfaden.net/HapiServerDemo/hapi&id=specBins

because it doesn't have property "centers".  However ranges is specified, which makes it okay.  One /or/ the other is required, not both required.

**Comment by rweigel** [comment]
I really need to fix the time-out issue.  The link you gave does not show
problem because of 200 ms timeout.

**Comment by rweigel** [comment]
https://github.com/hapi-server/verifier-nodejs/issues/4

**Comment by jbfaden** [comment]
I've been able to check out my own verifier and tweak the schema so that neither is required.  Also note that units was not marked as required but it is now.  This is in verifier-nodejs/schemas/HAPI-data-access-schema-1.1.json, so maybe 1.1 didn't require units but 2.0 does.  

Bob, could you advise on how we should handle this?  Should I start a 2.0 schema?  Also, I assume there's a semantic check I can do to check that either centers or ranges is present.  Can you point me to where this would be added?

**Comment by rweigel** [comment]
The 2.0 schema has the fix for requiring units and requiring bins or centers or both. The draft is posted and the units/bins/centers section is at https://github.com/hapi-server/verifier-nodejs/blob/master/schemas/HAPI-data-access-schema-2.0.json#L223

The verifier repository and server will be updated once this issue is settled: https://github.com/hapi-server/data-specification/issues/54

**Comment by jbfaden** [comment]
I thought about trying to fix this over the weekend, and I'll be curious 
how you handled the either bins-or-centers logic.
Jeremy

**Comment by rweigel** [comment]
Version 2.0 now has this fix eaee6cd877f4b8cd5d0026b9bffdc6c28a0e82af
